##Kotlin
#kotlin.code.style=official
#kotlin.daemon.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g
#kotlin.apple.xcodeCompatibility.nowarn=true
#
##Gradle
#org.gradle.jvmargs=-Xmx8g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
#org.gradle.configuration-cache=false
#org.gradle.caching=true
#
##Android
#android.nonTransitiveRClass=true
#android.useAndroidX=true
#kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true

#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.apple.xcodeCompatibility.nowarn=true

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.configuration-cache=false
org.gradle.caching=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.apple.deprecated.allowUsingEmbedAndSignWithCocoaPodsDependencies=true