package org.example.project

import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.interaction.MutableInteractionSource
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.Badge
import androidx.compose.material3.BadgedBox
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import cafe.adriel.voyager.navigator.LocalNavigator
import cafe.adriel.voyager.navigator.Navigator
import org.example.project.domain.model.Chat
import org.example.project.domain.model.PermissionItem
import org.example.project.domain.model.User
import org.example.project.presentation.base.CustomHeader
import org.example.project.presentation.base.CustomMultiLineTextField
import org.example.project.presentation.base.CustomSelectionButton
import org.example.project.presentation.base.CustomTextField
import org.example.project.presentation.base.DividedButton
import org.example.project.presentation.base.SearchField
import org.example.project.presentation.base.theme.BackgroundColor
import org.example.project.presentation.base.theme.ButtonHeight
import org.example.project.presentation.base.theme.ChatIconSize
import org.example.project.presentation.base.theme.ChatMessageColor
import org.example.project.presentation.base.theme.ChatSmallIconSize
import org.example.project.presentation.base.theme.ContainerPadding
import org.example.project.presentation.base.theme.DividerColor
import org.example.project.presentation.base.theme.HintTextColor
import org.example.project.presentation.base.theme.NormalTextSize
import org.example.project.presentation.base.theme.PrimaryColor
import org.example.project.presentation.base.theme.SmallIconButtonSize
import org.example.project.presentation.base.theme.SmallIconSize
import org.example.project.presentation.base.theme.SmallTextSize
import org.example.project.presentation.base.theme.SpaceLarge
import org.example.project.presentation.base.theme.SpaceMedium
import org.example.project.presentation.base.theme.SpaceSmall
import org.example.project.presentation.base.theme.SpaceUltraSmall
import org.example.project.presentation.base.theme.TextColor
import org.example.project.presentation.base.theme.TextFieldHeight
import org.example.project.presentation.base.theme.UltraSmallTextSize
import org.example.project.presentation.monitoring.ClientPermissionStateScreen
import org.example.project.ui.OnPrimaryColor
import org.example.project.ui.TonalButtonContainerColor
import org.jetbrains.compose.resources.painterResource
import org.jetbrains.compose.resources.stringResource
import tikoncha_parents.composeapp.generated.resources.Res
import tikoncha_parents.composeapp.generated.resources.alarm
import tikoncha_parents.composeapp.generated.resources.bolaning_ilovasini_sozligi
import tikoncha_parents.composeapp.generated.resources.chat_ai_icon
import tikoncha_parents.composeapp.generated.resources.chat_icon
import tikoncha_parents.composeapp.generated.resources.farzandingiz
import tikoncha_parents.composeapp.generated.resources.ism_orqali_qidirish
import tikoncha_parents.composeapp.generated.resources.kuzatuv
import tikoncha_parents.composeapp.generated.resources.permission_adminstration
import tikoncha_parents.composeapp.generated.resources.permission_battery_2bars_1
import tikoncha_parents.composeapp.generated.resources.permission_camera
import tikoncha_parents.composeapp.generated.resources.permission_floating
import tikoncha_parents.composeapp.generated.resources.permission_location
import tikoncha_parents.composeapp.generated.resources.permission_message_notif
import tikoncha_parents.composeapp.generated.resources.permission_monitoring
import tikoncha_parents.composeapp.generated.resources.permission_usage_time
import tikoncha_parents.composeapp.generated.resources.person
import tikoncha_parents.composeapp.generated.resources.suhbat
import tikoncha_parents.composeapp.generated.resources.tanlang
import tikoncha_parents.composeapp.generated.resources.yuborish
import uz.saidburxon.newedu.presentation.base.CustomButton
import uz.saidburxon.newedu.presentation.base.CustomText
import kotlin.times






